######################################################################
#
# File name : basic_mul_top_compile.do
# Created on: Thu May 08 15:33:27 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vlib modelsim_lib/work
vlib modelsim_lib/msim

vlib modelsim_lib/msim/xil_defaultlib

vmap xil_defaultlib modelsim_lib/msim/xil_defaultlib

vlog  -incr -mfcu -work xil_defaultlib  \
"../../../../../source/basic_6x6_mul/full_adder.v" \
"../../../../../source/basic_6x6_mul/half_adder.v" \
"../../../../../source/basic_6x6_mul/mul_row.v" \
"../../../../../source/basic_6x6_mul/basic_mul_top.v" \


# compile glbl module
vlog -work xil_defaultlib "glbl.v"

quit -force

