######################################################################
#
# File name : basic_mul_top_wave.do
# Created on: Thu May 08 15:33:29 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
