######################################################################
#
# File name : basic_mul_top_simulate.do
# Created on: Thu May 08 15:33:29 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.basic_mul_top xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {basic_mul_top_wave.do}

view wave
view structure
view signals

do {basic_mul_top.udo}

run 1000ns
