######################################################################
#
# File name : tb_basic_6x6_mul_wave.do
# Created on: Thu May 08 15:33:43 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
if { [catch {[add wave *]}] } {}
add wave /glbl/GSR
