######################################################################
#
# File name : tb_basic_6x6_mul_simulate.do
# Created on: Thu May 08 16:23:26 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
vsim -voptargs="+acc" -L xil_defaultlib -L unisims_ver -L unimacro_ver -L secureip -lib xil_defaultlib xil_defaultlib.tb_basic_6x6_mul xil_defaultlib.glbl

set NumericStdNoWarnings 1
set StdArithNoWarnings 1

do {tb_basic_6x6_mul_wave.do}

view wave
view structure
view signals

do {tb_basic_6x6_mul.udo}

run 1000ns
