######################################################################
#
# File name : tb_basic_6x6_mul.udo
# Created on: Thu May 08 15:33:43 +0800 2025
#
# Auto generated by Vivado for 'behavioral' simulation
#
######################################################################
